
All these files must be in the same directory, and should be the only files in
the directory.

dummy*
======

    It is ok if these files don't exist. They are temporaries used by mklfs.sh


library-check.sh
================

    Script from the preface of the book (section vii).

    Used inside mklfs.sh


md5sums-no-kernel
=================

    File mentioned in section 3.1 of the book. The md5 for the linux kernel
    is not included because it downloaded separately.

    Used by mklfs.sh


mklfs.conf
==========

    Configuration file generated by mklfs.sh, and used in subsequent calls to
    mklfs.sh . Can be edited by hand, though.


mklfs.log
=========

    Log file of the actions taken and events happening inside mklfs.sh.


mklfs.sh
========

    Main script that guides and helps through the building and instalation of
    an LFS system.


version-check.sh
================

    Script from the preface of the book (section vii).

    Used inside mklfs.sh


wget-list-no-kernel
===================

    File mentioned in section 3.1 of the book. This file was modified; the
    download location of file-5.19.tar.gz was changed to a mirror, following
    the suggestion made in the note in section 3.2. Also, the URL for
    downloading the linux kernel is not included, because it is downloaded
    separately.

    Used by mklfs.sh
